src/rIdeal.WebApplication/rIdeal.WebApplication/Models/FileManagerViewModels.cs
using System.ComponentModel.DataAnnotations;
using System.Web.UI.WebControls;

namespace IdeAl.WebApplication.Models
{
    public class FileManagerViewModels
    {
        [Required(ErrorMessage = "Поле \"{0}\" должно быть заполнено.")]
        [StringLength(50, ErrorMessage = "{0} должно быть не более {1} символов.")]
        [RegularExpression(@"[^ \/:*?""<>|]+", ErrorMessage = "Имя файла не должно содержать следующих знаков: \\ / : * ? \" < > |")]
        [Display(Name = "Имя файла")]
        public string NewFileName { get; set; }
    }
}

src/rIdeal.WebApplication/rIdeal.WebApplication/Controllers/FileManagerController.cs
using System.Net.Mime;
using System.Web.Mvc;
using IdeAl.WebApplication.Hubs;
using Microsoft.AspNet.Identity;

namespace IdeAl.WebApplication.Controllers
{
    [Authorize]
    public class FileManagerController : Controller
    {
        private readonly ApplicationLogic _application;

        public FileManagerController(ApplicationLogic application)
        {
            _application = application;
        }

        [HttpGet]
        public ActionResult _ToolbarPartial()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult Download(string fileName)
        {
            var data = _application.DownloadFile(User.Identity.GetUserId(), fileName);
            if (data == null)
                return HttpNotFound(string.Format("Не удалось получить файл с именем '{0}' ", fileName));
            return File(data, MediaTypeNames.Application.Octet, fileName);
        }
	}
}

src/rIdeal.WebApplication/rIdeal.WebApplication/Views/FileManager/_ToolbarPartial.cshtml
@model IdeAl.WebApplication.Models.FileManagerViewModels

<style>
    .toolbar {
        width: 250px;
        height: 600px;
        top: 25px;
    }

    .file-list {
        position: absolute;
        left: 0;
        right: 0;
        top: 80px;
        bottom: 0;
        overflow-x: hidden;
        overflow-y: auto;
        margin: 0;
        padding: 0;
        cursor: default
    }
</style>

<form id="formToolbar">
    <div class="toolbar">
        <div class="form-group">
            <h4>Список файлов</h4>
            <div class="btn-group-sm">
                <button type="button" id="btn-refresh-file-list" class="btn btn-default" title="Обновить список"><span class="glyphicon glyphicon-refresh"></span></button>
                <button type="button" id="btn-create-file-window" class="btn btn-default" title="Создать файл"><span class="glyphicon glyphicon-file"></span></button>
                <button type="button" id="btn-open-file" class="btn btn-default" disabled="disabled" title="Открыть файл"><span class="glyphicon glyphicon-folder-open"></span></button>
                <button type="button" id="btn-save-file" class="btn btn-default" disabled="disabled" title="Сохранить файл"><span class=" glyphicon glyphicon-floppy-disk"></span></button>
                <button type="button" id="btn-download-file" data-action="@Url.Action("Download", "FileManager", new {fileName = "__fileName__"})" class="btn btn-default" disabled="disabled" title="Скачать файл"><span class="glyphicon glyphicon-download-alt"></span></button>
                <button type="button" id="btn-delete-file" class="btn btn-default btn-danger" disabled="disabled" title="Удалить файл"><span class="glyphicon glyphicon-remove"></span></button>
            </div>
        </div>
        <div class="list-group well file-list">
        </div>
    </div>

    <!--Модальное окно для ввода имени файла-->
    <div class="modal modal-content modal-dialog" id="modal-window-create-file" style="position: fixed; overflow-y: hidden; top: 30%">
        <div class="modal-header" style="padding: 5px 10px;">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4>Создание нового файла</h4>
        </div>
        <div class="modal-body">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @id = "error-creating-file" })
            <div class="form-group">
                @Html.LabelFor(m => m.NewFileName)
                @Html.TextBoxFor(m => m.NewFileName, new { @class = "form-control", @style = "max-width: 100%" })
            </div>
        </div>
        <div class="modal-footer" style="margin: 0; padding: 10px; background-color: #f5f5f5">
            <button type="button" class="btn btn-primary" id="btn-create-file">Создать</button>
            <button type="button" class="btn btn-default" id="btn-cancel-create-file" data-dismiss="modal" aria-hidden="true">Отмена</button>
        </div>
    </div>
</form>